import Header from "@/component/header/header";
import SideBar from "@/component/sidebar/sidebar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "DANA COMPANY",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <div className="mainnn">
                    <SideBar />
                    <div className="mainnn-children2">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
